import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';
import './globals.css';
import Header from './components/Header';
import { NextAuthProvider } from './lib/next-auth/provider';
import { Suspense } from 'react';
import LoadingSpinner from './components/LoadingSpinner';

const notoSansJp = Noto_Sans_JP({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Book commerce',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body className={`${notoSansJp.className}`}>
        <NextAuthProvider>
          <Header />
          <Suspense fallback={<LoadingSpinner />}>{children}</Suspense>
        </NextAuthProvider>
      </body>
    </html>
  );
}
